name: Clockwork
description: Stuff I make and say
url: http://clockwork.fr
markdown: kramdown
include:     ['.htaccess']

highlighter: pygments
pygments: true
permalink: /:year/:month/:title.html
paginate: 5
#paginate_path: "blog/page:num"


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
  input: GFM

  