baseURL = "https://yozy.net/"
languageCode = "en-us"
title = "yozy//NET"
theme = "clockwork2"

[pagination]
pagerSize = 10

pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "monokai"
pygmentsUseClasses = true

[permalinks]
posts = "/:year/:month/:title/"
micros = "/micro/:filename/"
pages = "/pages/:slug"

[outputs]
home = ["html", "rss"]

[markup.goldmark.renderer]
unsafe=true

[mediaTypes]
[mediaTypes."application/rss"]
suffixes = ["xml"]

[outputFormats]

[outputFormats.rss]
mediatype = "application/rss"
baseName = "feed"

[privacy.youtube]
disable = false
privacyEnhanced = true
