baseURL = "https://yozy.net/"
languageCode = "en-us"
title = "yozy//NET"
theme = "clockwork2"

[pagination]
pagerSize = 10

pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "monokai"
pygmentsUseClasses = true

[permalinks]
posts = "/:year/:month/:title/"
micros = "/micro/:filename/"
pages = "/pages/:slug"

[outputs]
home = ["html", "rss"]

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'gruvbox-light'
    tabWidth = 4

[mediaTypes]
[mediaTypes."application/rss"]
suffixes = ["xml"]

[outputFormats]

[outputFormats.rss]
mediatype = "application/rss"
baseName = "feed"

[privacy.youtube]
disable = false
privacyEnhanced = true
