baseURL = "https://yozy.net/"
languageCode = "en-us"
title = "yozy//NET"
theme = "clockwork"

paginate = 10

RSSURI = "feed.xml"

pygmentscodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[permalinks]
posts = "/:year/:month/:title/"
micros = "/:filename/"
pages = "/pages/:slug"

[outputs]
home = ["html","rss", "jsonfeed"]

[mediaTypes]
[mediaTypes."application/rss"]
suffix = "xml"

[mediaTypes."application/json"]
suffix = "json"

[outputFormats]

[outputFormats.rss]
mediatype = "application/rss"
baseName = "feed"

[outputFormats.jsonfeed]
mediaType = "application/json"
baseName = "feed"
isPlainText = true
